  <main>
    <section>
      <div class="container image-blur">
        <div class="row">
          <div class="col-lg-8  m-auto p-4 rounded bg-light bg-opacity-75 px-5 ps-5 text-start  " style="--bs-bg-opacity: 0.9!important; ">
            <h1> Impressum </h1>
            <p> Max Musterstraße 1 </p>
            <p> A-1210 Wien </p>

            <p> Tel.:+43 1 234 567 </p>
            <p>E-Mail:max.muster@gmx.at</p>
            <p>Firmenbuchnummer: 123 456x</p>
            <p>Firmenbuchgericht: Gerichtsstand Wien</p>
            <p> Aufsichtsbehörde: Magistrat der Stadt Wien</p>
            <p>Mitgliedschaft: WKO, ÖHV</p>
            <p>UID-Nummer: ATU12345678</p>
            <p> Inhaltlich Verantwortliche gemäß § 55 Abs. 2 RStV: Panda </p>
            <!-- und https://devpractical.com/bootstrap-sticky-footer/-->
            <div class=" pt-3">
              <figure class="figure col-sm-4 ">
                <div class="text-center">
                  <img src="res/img/ben.jpg" class="figure-img img-fluid rounded  " alt="One of the owners, Ben">
                  <figcaption class="text-dark" class="figure-caption">Ben</figcaption>
              </figure>
              <figure class="figure col-sm-4 ">
                <img src="res/img/alex.jpg" class=" ms-3 figure-img img-fluid rounded  " alt="One of the owners, Alex">
                <figcaption class="text-dark" class="figure-caption">Alex</figcaption>
              </figure>
              <div class="text-start">
                Bildernachweis:<p> Foto von <a href="https://unsplash.com/@ralphkayden?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Ralph (Ravi) Kayden</a> auf <a href="https://unsplash.com/de/fotos/zSG-kd-L6vw?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a></p>
                <p>
                  Foto von <a href="https://unsplash.com/@austindistel?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Austin Distel</a> auf <a href="https://unsplash.com/de/fotos/7uoMmzPd2JA?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a></p>
                Foto von <a href="https://unsplash.com/@brucemars?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">bruce mars</a> auf <a href="https://unsplash.com/de/fotos/8YG31Xn4dSw?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a></p>
                <p>
                Foto von <a href="https://unsplash.com/@madseneqvist?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Mads Eneqvist</a> auf <a href="https://unsplash.com/de/fotos/zqiE16q_Ju0?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
</p><p>
                Foto von <a href="https://unsplash.com/@yibeigeng?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Yibei Geng</a> auf <a href="https://unsplash.com/de/fotos/-UdYbiywGeg?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
                </p><p>
                Foto von <a href="https://unsplash.com/@loewe?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Loewe Technology</a> auf <a href="https://unsplash.com/de/fotos/wVx56Y9Ro0o?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
                </p><p>
                Foto von <a href="https://unsplash.com/fr/@3dottawa?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Point3D Commercial Imaging Ltd.</a> auf <a href="https://unsplash.com/de/fotos/oxeCZrodz78?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
                </p>
  
  
  
                  Logo generated by the Image Creation AI <a href="https://openai.com/dall-e-2/">DALL-E 2</a>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
